name: cobrando-lat-prod

services:
  django:
    restart: always
    build:
      context: ../../ # <- Esto apunta a la raÃ­z del repo
      dockerfile: docker/prod/Dockerfile
    env_file:
      - ../../.env
    volumes:
      - "${DOCKER_PROD_DJANGO_STATICFILES_PATH}:/app/staticfiles"
      - "${DOCKER_PROD_DJANGO_UPLOADS_PATH}:/app/uploads"
    ports:
      - "${DOCKER_PROD_DJANGO_PORT}:8000"
    command: >
      sh -c "
      python manage.py tailwind install && python manage.py tailwind build &&

      if [ \"$DOCKER_PROD_DJANGO_RUN_MIGRATIONS\" = \"true\" ]; then
          echo 'Ejecutando migraciones...'
          python manage.py migrate
      fi &&

      if [ "$DOCKER_PROD_DJANGO_RUN_COLLECTSTATIC" = "true" ]; then
          echo 'Ejecutando collectstatic...'
          python manage.py collectstatic --noinput
      fi &&

      echo 'Iniciando gunicorn' &&
      gunicorn --bind 0.0.0.0:8000 --workers ${DOCKER_PROD_DJANGO_GUNICORN_WORKERS:-3} --threads ${DOCKER_PROD_DJANGO_GUNICORN_THREADS:-3} --timeout 120 cobrando_lat.wsgi:application &&
      echo 'Gunicorn finalizado.'
      "